'use strict';
const KEY='joe_room_2026_v2', LEGACY='joe_reglaze_choices_v1';
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const costs=[['reglaze','Professional reglaze','Tub + tile. Replace this allowance with the written scope.',1800],['vanity','Vanity · bought, in the garage','Top + sink included. Enter the receipt amount if you want it in the full project total.',0],['flooring','Flooring','Keep existing tile: no replacement allowance. A new floor needs a quote for material, prep, labor and transitions.',0],['faucet','Chrome faucet','Check what you already have before buying.',200],['accents','Optional brass accents','Additional accessories or matching hardware; quote separately from the retained chrome faucet.',0],['paint','Paint + preparation','Paint above the tile and repair allowance.',150],['mirror','Mirror','A planning allowance; update for your chosen model.',120],['light','Lighting','Include any electrical labor in the quote.',300],['mount','Mounting + plumbing','Confirm blocking, drain fit and installation scope.',350],['supplies','Supplies + finishing','Protection, sealants, hardware and small surprises.',200]];
const defaults={wall:'greige',metal:'chrome',floor:'keep',mirror:'framed',width:72,length:96,tubLength:60,tubDepth:30,doorWidth:22,measured:false,ceiling:5000,reserve:15,notes:{likes:'',changes:'',questions:''},steps:[],pinned:'',costs:Object.fromEntries(costs.map(([k,l,d,v])=>[k,{amount:v,status:k==='vanity'?'paid':'allowance'}]))};
let state=structuredClone(defaults), sound=false, view='vanity';
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved)state={...state,...saved,notes:{...state.notes,...saved.notes},costs:{...state.costs,...saved.costs}};else{const old=JSON.parse(localStorage.getItem(LEGACY)||'{}');state.width=old.A||72;state.length=old.B||96;state.floor=old.floor||'keep';state.mirror=old.mirror||'framed';state.metal=old.accent||'chrome';state.wall=old.wall&&/a[0-9a-f]|b[0-9a-f]/i.test(old.wall)?'greige':'greige'}}catch{}
state.costs.mirror.forChoice=state.costs.mirror.forChoice||'framed';state.costs.flooring.forChoice=state.costs.flooring.forChoice||'keep';state.costs.vanity.status='paid';state.tubLength=state.tubLength||60;state.doorWidth=state.doorWidth||22;
try{const shared=JSON.parse(localStorage.getItem(LEGACY)||'{}');if(shared.A>=40&&shared.A<=180)state.width=shared.A;if(shared.B>=60&&shared.B<=240)state.length=shared.B}catch{}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function tick(){if(!sound)return;try{const a=window.audioCtx||(window.audioCtx=new(window.AudioContext||window.webkitAudioContext)());const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=620;g.gain.setValueAtTime(.025,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.18);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.18)}catch{}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));let old={};try{old=JSON.parse(localStorage.getItem(LEGACY)||'{}')}catch{};localStorage.setItem(LEGACY,JSON.stringify({...old,wall:{white:'#f2eee5',greige:'#c6bdaf',sage:'#a5b5a0'}[state.wall],floor:state.floor,mirror:state.mirror,accent:state.metal,sink:'integrated',...JoeRoomGeometry(state).legacy}));$('saved').textContent='Saved on this device ✓'}catch{$('saved').textContent='Not saved · download a copy';toast('Browser storage is unavailable. Download your decisions to keep them.')}}
function tab(id){document.querySelectorAll('.panel').forEach(x=>x.hidden=x.id!==id);document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===id);if(b.dataset.tab===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});history.replaceState(null,'','#'+id);if(id==='fit')drawPlan();if(id!=='room')$('walk').querySelector('iframe').src='about:blank';else if(view==='3d')picture();}
document.querySelectorAll('[data-tab],[data-go]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab||b.dataset.go)));
function picture(){document.querySelectorAll('[data-wall]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.wall===state.wall)));document.querySelectorAll('[data-metal]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.metal===state.metal)));$('floor').value=state.floor;$('mirror').value=state.mirror;$('pinned').textContent=state.pinned?'Kept: '+state.pinned:'Nothing is ordered when you make a choice.';if(view==='3d'){save();$('photoCaption').textContent='Illustrative 3D model. Drag to orbit. Floor and mirror choices appear here.';$('walk').querySelector('iframe').src='room3d.html?v=20260907-7';return}const tub=view==='tub';$('after').src=tub?'assets/after_tub.jpg':state.mirror==='framed'?`assets/style_${state.wall}_${state.metal}.jpg`:`assets/mirror_${state.wall}_${state.metal}_${state.mirror}.jpg`;$('before').src=tub?'assets/hall_tub.jpg':'assets/hall_vanity.jpg';$('after').alt=tub?'AI concept of Joe’s reglazed tub wall':`AI concept of Joe’s vanity wall in ${state.wall} with ${state.metal} accents and ${state.mirror} mirror`;$('photoCaption').textContent=tub?'Tub concept: white reglaze and retained sliders. Paint / metal controls preview the vanity wall.':'Real room photo + AI design concept. Finish preview, not a measured construction drawing.';floorPreview();}
document.querySelectorAll('[data-wall]').forEach(b=>b.onclick=()=>{state.wall=b.dataset.wall;save();$('compare').value=0;$('compare').oninput();picture();tick()});document.querySelectorAll('[data-metal]').forEach(b=>b.onclick=()=>{state.metal=b.dataset.metal;save();$('compare').value=0;$('compare').oninput();picture();tick()});['floor','mirror'].forEach(id=>$(id).onchange=()=>{state[id]=$(id).value;save();$('compare').value=0;$('compare').oninput();if(view==='tub')document.querySelector('[data-view="vanity"]').click();picture();budget();tick();if(view!=='3d')toast(id==='mirror'?'Mirror updated in the Possible view.':'Floor updated in the Possible view.')});
function floorPreview(target='floorPreview',force=false){
 const svg=$(target),hide=state.floor==='keep'||(!force&&view!=='vanity');svg.style.display=hide?'none':'block';if(hide)return;
 const planes={white_chrome:[[534,809],[799,809],[920,1045],[413,1045]],white_brass:[[523,807],[790,801],[910,1045],[402,1045]],greige_chrome:[[552,835],[812,835],[903,1045],[445,1045]],greige_brass:[[559,781],[812,781],[932,1045],[436,1045]],sage_chrome:[[530,823],[804,826],[904,1045],[396,1045]],sage_brass:[[551,797],[806,797],[927,1045],[411,1045]]};
 const q=planes[state.wall+'_'+state.metal],oak=state.floor==='oak';
 const point=(u,v)=>{const l=[q[0][0]+v*(q[3][0]-q[0][0]),q[0][1]+v*(q[3][1]-q[0][1])],r=[q[1][0]+v*(q[2][0]-q[1][0]),q[1][1]+v*(q[2][1]-q[1][1])];return[l[0]+u*(r[0]-l[0]),l[1]+u*(r[1]-l[1])].map(n=>n.toFixed(1)).join(',')};
 let tiles='';const rows=oak?[0,.3,1]:[0,.19,.43,.71,1],cols=oak?6:3;
 for(let y=0;y<rows.length-1;y++)for(let x=0;x<cols;x++){
 const color=oak?['#b6986f','#c5a67d','#bba077'][(x+y)%3]:['#817f75','#8a877c','#79796f'][(x+y)%3];
 tiles+=`<polygon points="${point(x/cols,rows[y])} ${point((x+1)/cols,rows[y])} ${point((x+1)/cols,rows[y+1])} ${point(x/cols,rows[y+1])}" fill="${color}" stroke="${oak?'#9f815f':'#b9b6aa'}" stroke-width="${oak?1:2}"/>`;
 }
 svg.innerHTML=`<defs><clipPath id="floorClip"><polygon points="${q.map(p=>p.join(',')).join(' ')}"/></clipPath><pattern id="floorGrain" width="${oak?85:220}" height="400" patternUnits="userSpaceOnUse">${oak?'<image href="assets/oak.jpg" width="85" height="400" preserveAspectRatio="none"/>':'<path d="M10 30Q100 10 180 165M40 310Q120 170 210 200" fill="none" stroke="#c2beb0" stroke-width="1.5"/>'}</pattern><linearGradient id="floorShadow"><stop offset="0" stop-color="#000" stop-opacity=".1"/><stop offset=".45" stop-color="#fff" stop-opacity=".03"/><stop offset="1" stop-color="#000" stop-opacity=".3"/></linearGradient></defs><g clip-path="url(#floorClip)">${tiles}<rect x="380" y="750" width="580" height="300" fill="url(#floorGrain)" opacity="${oak?.25:.3}"/><rect x="380" y="750" width="580" height="300" fill="url(#floorShadow)"/></g>`;
 if(!force)$('photoCaption').textContent='Your finish combination · illustrative photo preview. Compare real samples before choosing.';
 if(force)svg.innerHTML=svg.innerHTML.replaceAll('floorClip','budgetFloorClip').replaceAll('floorGrain','budgetFloorGrain').replaceAll('floorShadow','budgetFloorShadow');
}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('selected',x===b));$('picture').hidden=view==='3d';$('walk').hidden=view!=='3d';$('compareLabel').hidden=view==='3d';if(view!=='3d')$('walk').querySelector('iframe').src='about:blank';picture();});
$('compare').oninput=()=>{const v=+$('compare').value;$('beforeclip').style.clipPath=`inset(0 ${100-v}% 0 0)`;$('divider').style.left=v+'%';$('compareValue').textContent=v===0?'All possibility':v===100?'The original':`${v}% original`};
$('reveal').onclick=()=>{if(view==='3d')document.querySelector('[data-view="vanity"]').click();const on=$('picture').classList.toggle('evening');$('reveal').textContent=on?'Back to daylight ↗':'Evening light ↗';if(on){$('compare').value=0;$('compare').oninput();toast('The room you saw the possibility in. ♡');if(sound){const a=new Audio('assets/audio/warming_heart.mp3');a.play().catch(()=>tick())}}};
$('pin').onclick=()=>{state.pinned=`${{white:'Warm white',greige:'Soft greige',sage:'Quiet sage'}[state.wall]} + ${state.metal} · ${state.floor} floor · ${state.mirror} mirror`;save();picture();toast('Kept for you, Joe.');tick()};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',sound);tick()};$('big').onclick=()=>{const on=document.body.classList.toggle('big');$('big').setAttribute('aria-pressed',on);try{localStorage.setItem('joe_bigtype_v2',on?'1':'0')}catch{}};try{if(localStorage.getItem('joe_bigtype_v2')!=='0'){$('big').setAttribute('aria-pressed','true');document.body.classList.add('big')}}catch{}
function drawPlan(){const g=JoeRoomGeometry(state),w=g.width,l=g.length,t=g.tubDepth,tl=g.tubLength,dw=state.doorWidth||22,scale=Math.min(480/w,390/l),ox=(700-w*scale)/2,oy=65;const X=v=>ox+v*scale,Y=v=>oy+v*scale;
$('gap').textContent=g.gap.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+'″';$('fitNote').textContent=(state.measured?'From your entered measurements. ':'Estimated until you measure. ')+(g.gap<0?'Fixture depths overlap. Recheck the dimensions.':`L-shaped floor: about ${g.area.toFixed(1)} sq ft, excluding the hall closet. This gap does not include drawer travel.`);
const outline=g.points.map(([x,y])=>X(x)+','+Y(y)).join(' '),vanY=Math.max(30,l-48.5-8);
$('plan').innerHTML=`<defs><pattern id="closethatch" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#a7c883" stroke-width="1"/></pattern></defs><rect x="${ox}" y="${Y(tl)}" width="${t*scale}" height="${(l-tl)*scale}" fill="url(#closethatch)"/><polygon points="${outline}" fill="#fafcf7" stroke="#5185af" stroke-width="5"/><rect x="${ox}" y="${oy}" width="${t*scale}" height="${tl*scale}" fill="#dfebf4" stroke="#89abc5" stroke-width="2"/><rect x="${X(3)}" y="${Y(5)}" width="${(t-6)*scale}" height="${(tl-10)*scale}" rx="22" fill="#fff"/><line x1="${X(t)}" y1="${oy}" x2="${X(t)}" y2="${Y(tl)}" stroke="#8aa4a1" stroke-width="3"/><text x="${X(t/2)}" y="${Y(tl/2)}" text-anchor="middle" fill="#253b34" font-size="17" transform="rotate(-90 ${X(t/2)} ${Y(tl/2)})">Tub · flush in corner</text><text x="${X(t/2)}" y="${Y(tl+(l-tl)/2)-7}" text-anchor="middle" font-size="16" fill="#59604f">HALL</text><text x="${X(t/2)}" y="${Y(tl+(l-tl)/2)+14}" text-anchor="middle" font-size="16" fill="#59604f">CLOSET</text><rect x="${X(w-18.75)}" y="${Y(vanY)}" width="${18.75*scale}" height="${48.5*scale}" fill="#cfbfa5" stroke="#65725e"/><text x="${X(w-9)}" y="${Y(vanY+24.25)}" text-anchor="middle" font-size="15" fill="#253b34" transform="rotate(-90 ${X(w-9)} ${Y(vanY+24.25)})">48½″ vanity · bought</text><rect x="${X(w-10)}" y="${Y(4)}" width="${9*scale}" height="${20*scale}" rx="4" fill="#fff" stroke="#99a596"/><ellipse cx="${X(w-18)}" cy="${Y(14)}" rx="${12*scale}" ry="${9*scale}" fill="#fff" stroke="#99a596"/><text x="${X(w-17)}" y="${Y(32)}" text-anchor="middle" font-size="15" fill="#253b34">Toilet corner</text><path d="M${X(t)} ${Y(tl-8)}H${X(w-18.75)}" stroke="#5185af" stroke-dasharray="4 3" stroke-width="2"/><text x="${X(t+(w-18.75-t)/2)}" y="${Y(tl-8)-9}" text-anchor="middle" font-size="16" fill="#315f80">${g.gap.toFixed(1)}″</text><path d="M${X(t+2)} ${Y(l)}H${X(Math.min(w-2,t+2+dw))}" stroke="#fafcf7" stroke-width="7"/><path d="M${X(t+2)} ${Y(l)}V${Y(l-dw)}M${X(t+2)} ${Y(l-dw)}A${dw*scale} ${dw*scale} 0 0 1 ${X(t+2+dw)} ${Y(l)}" fill="none" stroke="#357b9f" stroke-width="2"/><text x="${X(t+(w-t)/2)}" y="${Y(l)+30}" text-anchor="middle" font-size="16" fill="#253b34">~${dw}″ DOOR · measure</text><text x="350" y="30" text-anchor="middle" font-size="18" fill="#253b34">BACK / WINDOW · ${w}″ estimated width</text><text x="${X(w)+20}" y="${Y(l/2)}" font-size="17" fill="#253b34" transform="rotate(90 ${X(w)+20} ${Y(l/2)})">${l}″ outer length</text>`;
// Viewed from the entry: tub + hall closet on the right, vanity + toilet on the left.
const planMarkup=$('plan').innerHTML.replace(/<text\b([^>]*)>/g,(all,attrs)=>{const x=attrs.match(/\bx="([^"]+)"/);if(!x)return all;const old=attrs.match(/\btransform="([^"]*)"/);const transform=(old?old[1]+' ':'')+'translate('+(2*Number(x[1]))+' 0) scale(-1 1)';return '<text'+attrs.replace(/\s*transform="[^"]*"/,'')+' transform="'+transform+'">'});
$('plan').innerHTML='<g transform="translate(700 0) scale(-1 1)">'+planMarkup+'</g>';
}
['width','length','tubLength','tubDepth','doorWidth','ceiling','reserve'].forEach(id=>{$(id).value=state[id];$(id).onchange=()=>{const v=+$(id).value,min=+$(id).min,max=$(id).max?+$(id).max:1000000;if(!Number.isFinite(v)||v<min||v>max){$(id).value=state[id];toast('Please enter a number within the stated range.');return}if((id==='length'&&v<=state.tubLength)||(id==='tubLength'&&v>=state.length)||(id==='width'&&v<=state.tubDepth)||(id==='tubDepth'&&v>=state.width)){$(id).value=state[id];toast('The outer room must extend beyond the tub alcove.');return}state[id]=v;save();drawPlan();budget()}});$('measured').checked=state.measured;$('measured').onchange=()=>{state.measured=$('measured').checked;save();drawPlan()};
function budget(){let all=0,unpaid=0;for(const [id]of costs){const c=state.costs[id];const amount=(id==='flooring'&&state.floor==='keep'&&c.status!=='paid')||(id==='accents'&&state.metal==='chrome'&&c.status!=='paid')?0:c.amount;all+=amount;if(c.status!=='paid')unpaid+=amount}const contingency=unpaid*state.reserve/100,total=all+contingency,left=state.ceiling-total;$('total').textContent=money(total);$('remaining').textContent=money(unpaid+contingency);$('headroom').textContent=money(Math.abs(left));$('headroomLabel').textContent=left<0?'OVER CEILING':'ROOM LEFT';$('headroom').style.color=left<0?'#9e3b2a':'';$('budgetFill').style.width=Math.min(100,state.ceiling?total/state.ceiling*100:100)+'%';$('budgetFill').style.background=left<0?'#9e3b2a':'#86b459';$('budgetNote').textContent=`${money(contingency)} reserve on unpaid work. ${state.costs.vanity.amount===0?'Vanity is already bought; its receipt amount is not entered, so the full project total is incomplete.':'Vanity purchase is included in the project total and excluded from still-to-pay.'}${state.floor!=='keep'&&state.costs.flooring.amount===0?' New floor selected: replacement cost is not entered yet. Add a quote before relying on the total.':''}`;renderFinishBudget();}
for(const[id,title,desc]of costs){const row=document.createElement('div');row.className='costrow';row.dataset.cost=id;const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=title;const p=document.createElement('p');p.textContent=desc;d.append(strong,p);const l=document.createElement('label');l.textContent='Amount ($)';const input=document.createElement('input');input.type='number';input.min='0';input.step='1';input.value=state.costs[id].amount;input.setAttribute('aria-label',title+' amount');input.onchange=()=>{if(!Number.isFinite(+input.value)||+input.value<0){input.value=state.costs[id].amount;return}state.costs[id].amount=+input.value;if(id==='mirror')state.costs[id].forChoice=state.mirror;if(id==='flooring')state.costs[id].forChoice=state.floor;save();budget()};l.append(input);const sl=document.createElement('label');sl.textContent='Status';const s=document.createElement('select');for(const v of ['allowance','quoted','paid']){const o=document.createElement('option');o.value=v;o.textContent={allowance:'Estimate',quoted:'Written quote',paid:'Paid / owned'}[v];s.append(o)}s.value=state.costs[id].status;s.disabled=id==='vanity';s.onchange=()=>{state.costs[id].status=s.value;if(id==='mirror')state.costs[id].forChoice=state.mirror;if(id==='flooring')state.costs[id].forChoice=state.floor;save();budget()};sl.append(s);row.append(d,l,sl);$('costs').append(row)}
const steps=[['Measure the real room','JOE','Tape the walls and clearances. Photograph the vanity label in the garage.'],['Check the mounting and plumbing','JOE + INSTALLER','Confirm blocking, drain alignment, faucet fit and the included parts. Keep the existing door in place.'],['Choose the written scope','JOE','Compare reglaze quotes. Record coating, preparation, ventilation, warranty and cure time.'],['Prepare in the agreed order','TOGETHER + PRO','Agree paint, repairs, installation and refinishing sequence with the trades. Protect what stays.'],['Let the finish cure','FOLLOW THE COATING INSTRUCTIONS','Use the contractor’s written times for re-entry and use. Do not guess from a generic countdown.'],['Finish, check, enjoy','JOE + GORDON','Check leaks and fixings, fit the finishing touches, keep the aftercare sheet.']];
function renderSteps(){$('steps').replaceChildren();let done=0;steps.forEach(([title,who,desc],i)=>{const row=document.createElement('label');row.className='step';const c=document.createElement('input');c.type='checkbox';c.checked=!!state.steps[i];if(c.checked)done++;c.onchange=()=>{state.steps[i]=c.checked;save();renderSteps();tick()};const n=document.createElement('span');n.className='num';n.textContent=String(i+1).padStart(2,'0');const d=document.createElement('div');const h=document.createElement('strong');h.textContent=title;const p=document.createElement('p');p.textContent=who+' · '+desc;d.append(h,p);row.append(c,n,d);$('steps').append(row)});$('doneCount').textContent=done+' / 6';const next=steps.findIndex((_,i)=>!state.steps[i]);$('nextAction').textContent=next<0?'All six checked. Enjoy what you made, Joe.':'Next up: '+steps[next][0]+'.';}
for(const id of ['likes','changes','questions']){$(id).value=state.notes[id];$(id).oninput=()=>{state.notes[id]=$(id).value;save();if(id==='questions'){clearTimeout(questionTimer);questionTimer=setTimeout(showPlanAnswer,1200)}}}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'joes-room-v2',savedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='Joes-room-decisions.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Your decisions are ready to keep.')};
$('import').onchange=async()=>{try{const f=$('import').files[0];if(!f)return;if(f.size>100000)throw Error();const d=JSON.parse(await f.text());if(d.format!=='joes-room-v2'||!d.state)throw Error();const s=d.state;for(const[k,min,max]of [['width',40,180],['length',60,240],['tubDepth',20,48],['tubLength',40,100],['ceiling',0,1000000],['reserve',0,50]])if(typeof s[k]!=='number'||s[k]<min||s[k]>max)throw Error();for(const[k,v]of Object.entries({wall:['white','greige','sage'],metal:['chrome','brass'],floor:['keep','stone','oak'],mirror:['framed','lit','cabinet']}))if(!v.includes(s[k]))throw Error();for(const[k]of costs)if(k==='accents'&&!s.costs?.[k]){s.costs.accents={amount:0,status:'allowance'}}else if(!s.costs?.[k]||typeof s.costs[k].amount!=='number'||s.costs[k].amount<0||!['allowance','quoted','paid'].includes(s.costs[k].status))throw Error();if(s.length<=s.tubLength||s.width<=s.tubDepth||s.doorWidth!==undefined&&(!Number.isFinite(s.doorWidth)||s.doorWidth<18||s.doorWidth>42))throw Error();if(!s.notes||!['likes','changes','questions'].every(k=>typeof s.notes[k]==='string')||!Array.isArray(s.steps)||typeof s.pinned!=='string')throw Error();state={...defaults,...s};state.doorWidth=state.doorWidth||22;state.costs.vanity.status='paid';save();location.reload()}catch{$('importStatus').textContent='That file could not be restored. Your current choices are safe.'}};
$('print').onclick=$('printBudget').onclick=()=>window.print();window.addEventListener('storage',e=>{if(e.key===LEGACY)toast('The original planner changed. Reload to review your saved room dimensions.')} );
const finishNames={wall:{white:'Warm white',greige:'Soft greige',sage:'Quiet sage'},floor:{keep:'Keep white tile',stone:'Stone-look tile',oak:'Oak-look flooring'},mirror:{framed:'Framed mirror',lit:'Round backlit mirror',cabinet:'Medicine cabinet'}};
function renderFinishBudget(){
 $('budgetPhoto').src=state.mirror==='framed'?`assets/style_${state.wall}_${state.metal}.jpg`:`assets/mirror_${state.wall}_${state.metal}_${state.mirror}.jpg`;floorPreview('budgetFloor',true);
 $('budgetFinishTitle').textContent=finishNames.wall[state.wall]+' + '+(state.metal==='brass'?'brass accents':'chrome');
 const lines=[['Paint',`${finishNames.wall[state.wall]}. ${money(state.costs.paint.amount)} is the shared paint/preparation allowance; the color itself does not add a second charge.`],['Metal',state.metal==='brass'?`Brass accents selected. ${money(state.costs.accents.amount)} entered for optional hardware. The faucet stays chrome and has its own ${money(state.costs.faucet.amount)} line.`:`Chrome selected. ${money(state.costs.faucet.amount)} faucet allowance; unpaid optional brass accessories are excluded.`],['Floor',state.floor==='keep'?'Keep the white tile: no new-floor purchase is added. Any already-paid flooring remains part of total spending.':`${finishNames.floor[state.floor]}. ${money(state.costs.flooring.amount)} entered; get a quote covering material, prep, installation and transition height.`],['Mirror',`${finishNames.mirror[state.mirror]}. ${money(state.costs.mirror.amount)} entered. ${state.mirror==='lit'?'Confirm power and include an electrician’s quote if needed.':state.mirror==='cabinet'?'Confirm cabinet depth, mounting and whether it is recessed or surface mounted.':'Confirm size and wall mounting.'}`]];
 $('finishExplanations').replaceChildren();for(const [name,detail]of lines){const p=document.createElement('p'),strong=document.createElement('strong');strong.textContent=name+' · ';p.append(strong,document.createTextNode(detail));$('finishExplanations').append(p)}
 const warnings=[];if(state.floor!=='keep'&&(state.costs.flooring.amount===0||state.costs.flooring.forChoice!==state.floor))warnings.push('The selected floor still needs its own cost.');if(state.costs.mirror.forChoice!==state.mirror)warnings.push('The mirror amount belongs to an earlier choice; update it for this mirror.');if(state.metal==='brass'&&!state.costs.accents.amount)warnings.push('Brass accessory costs have not been entered.');
 $('finishQuoteWarning').textContent=warnings.length?'Not fully priced yet: '+warnings.join(' '):'Your entered amounts are shown below. Estimates remain estimates until replaced with written quotes.';
 if(warnings.length)$('budgetNote').textContent+=' '+warnings.join(' ');
}
let questionTimer;
function planAnswer(question){
 const q=question.toLowerCase().trim();if(q.length<4)return 'Ask about the floor, mirror, vanity, door, measurements, quotes or next steps. I’ll start with what this plan knows.';
 const a=[];
 if(/floor|tile|oak|stone|vinyl/.test(q))a.push(`${finishNames.floor[state.floor]} is selected. ${state.floor==='keep'?'Keeping it adds no new-floor purchase.':`The entered flooring amount is ${money(state.costs.flooring.amount)}${state.costs.flooring.amount===0?', so the replacement is not priced yet':''}. Confirm wet-area suitability, subfloor prep, installation and door/threshold height with the installer.`}`);
 if(/mirror|cabinet|backlit|light|electric|wir/.test(q))a.push(`${finishNames.mirror[state.mirror]} is selected, with ${money(state.costs.mirror.amount)} entered. ${state.mirror==='lit'?'A backlit mirror needs a suitable power connection; have an electrician confirm the product and location before buying. Add any wiring labor to Lighting.':state.mirror==='cabinet'?'Confirm width, depth and door opening above the vanity. Recessing requires checking the wall for framing, wiring and plumbing; the picture illustrates a surface-mounted option.':'A plain, unlit framed mirror does not need a power connection. Check its dimensions, fasteners and wall support; lighting is separate.'}${state.costs.mirror.forChoice!==state.mirror?' This amount was entered for a different mirror choice and needs updating.':''}`);
 if(/door|swing|closet|left|right|orient/.test(q))a.push(`The door is provisionally ${state.doorWidth}″ wide, still to verify with a tape, and stays beside the closet. Entering the room, the tub and closet are on your right; the vanity and toilet are on your left. The hinge is on the closet side. Verify the exact jamb offset and swing on site.`);
 if(/vanity|sink|top|drawer|fit|measur|wide|width|clearance/.test(q)){const g=JoeRoomGeometry(state);a.push(`The vanity is already bought and in the garage. The recorded Domani Stella model is 48½″ wide × 18¾″ deep, with its top and single sink included; check the box label. The current estimated tub-to-vanity gap is ${g.gap.toFixed(2)}″. Drawer travel, toilet clearance and mounting support still need on-site checks; this number is not an installation approval.`);}
 if(/budget|cost|price|money|afford|quote|paid|allowance/.test(q))a.push(`The budget currently shows ${$('remaining').textContent} still to pay, including the ${state.reserve}% reserve. The vanity is excluded from remaining purchases. A replacement floor or changed mirror may still be unpriced; read the selected-finish explanation above the budget before relying on the total.`);
 if(/reglaz|coating|cure|dry|ventila|paint|contractor|install/.test(q))a.push('Ask the installer for a written scope covering preparation, repairs, coating, ventilation, cure time and warranty. The contractor’s product-specific instructions determine when the room can be entered and used. The site does not substitute a generic cure countdown.');
 if(/next|start|first|help|order/.test(q))a.push('Start with the tape measurements and the vanity’s box label. Then confirm mounting/plumbing, obtain the written reglaze scope, and price the finishes you choose. The “What’s next” checklist keeps that order visible.');
 if(!a.length)a.push('I don’t have enough verified information to answer that specific question yet. I can help you frame the next step: include a photo, the relevant measurement or product model, and what decision you need to make. Your current plan is '+finishNames.wall[state.wall]+', '+finishNames.floor[state.floor]+', and '+finishNames.mirror[state.mirror]+'. Use the link below to ask Gordon and Astra to investigate it.');
 return a.join('\n\n');
}
function showPlanAnswer(){const question=$('questions').value;const p=document.createElement('p');p.textContent=planAnswer(question);$('questionAnswer').replaceChildren(p);const body='Joe’s bathroom question:\n'+question+'\n\nCurrent choices: '+finishNames.wall[state.wall]+', '+state.metal+', '+finishNames.floor[state.floor]+', '+finishNames.mirror[state.mirror]+'.\nEntered room: '+state.width+' × '+state.length+' inches. Door: approximately 22 inches, unverified.\n\nhttps://gordonusc.github.io/hall-bathroom-plan/';$('supportLink').href='mailto:gbellamy@gmail.com?subject='+encodeURIComponent('Joe’s bathroom: a little help')+'&body='+encodeURIComponent(body);}
$('answerQuestion').onclick=showPlanAnswer;

save();picture();drawPlan();budget();renderSteps();tab(['room','fit','money','build','notes'].includes(location.hash.slice(1))?location.hash.slice(1):'room');

showPlanAnswer();
