'use strict';
const KEY='joe_room_2026_v2', LEGACY='joe_reglaze_choices_v1';
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const costs=[['reglaze','Professional reglaze','Tub + tile. Replace this allowance with the written scope.',1800],['vanity','Vanity · bought, in the garage','Top + sink included. Enter the receipt amount if you want it in the full project total.',0],['flooring','Flooring','Keep existing tile: no replacement allowance. A new floor needs a quote for material, prep, labor and transitions.',0],['faucet','Chrome faucet','Check what you already have before buying.',200],['paint','Paint + preparation','Paint above the tile and repair allowance.',150],['mirror','Mirror','A planning allowance; update for your chosen model.',120],['light','Lighting','Include any electrical labor in the quote.',300],['mount','Mounting + plumbing','Confirm blocking, drain fit and installation scope.',350],['supplies','Supplies + finishing','Protection, sealants, hardware and small surprises.',200]];
const defaults={wall:'greige',metal:'chrome',floor:'keep',mirror:'framed',width:72,length:96,tubLength:60,tubDepth:30,measured:false,ceiling:5000,reserve:15,notes:{likes:'',changes:'',questions:''},steps:[],pinned:'',costs:Object.fromEntries(costs.map(([k,l,d,v])=>[k,{amount:v,status:k==='vanity'?'paid':'allowance'}]))};
let state=structuredClone(defaults), sound=false, view='vanity';
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved)state={...state,...saved,notes:{...state.notes,...saved.notes},costs:{...state.costs,...saved.costs}};else{const old=JSON.parse(localStorage.getItem(LEGACY)||'{}');state.width=old.A||72;state.length=old.B||96;state.floor=old.floor||'keep';state.mirror=old.mirror||'framed';state.metal=old.accent||'chrome';state.wall=old.wall&&/a[0-9a-f]|b[0-9a-f]/i.test(old.wall)?'greige':'greige'}}catch{}
state.costs.vanity.status='paid';state.tubLength=state.tubLength||60;
try{const shared=JSON.parse(localStorage.getItem(LEGACY)||'{}');if(shared.A>=40&&shared.A<=180)state.width=shared.A;if(shared.B>=60&&shared.B<=240)state.length=shared.B}catch{}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function tick(){if(!sound)return;try{const a=window.audioCtx||(window.audioCtx=new(window.AudioContext||window.webkitAudioContext)());const o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=620;g.gain.setValueAtTime(.025,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.18);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.18)}catch{}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));let old={};try{old=JSON.parse(localStorage.getItem(LEGACY)||'{}')}catch{};localStorage.setItem(LEGACY,JSON.stringify({...old,wall:{white:'#f2eee5',greige:'#c6bdaf',sage:'#a5b5a0'}[state.wall],floor:state.floor,mirror:state.mirror,accent:state.metal,sink:'integrated',...JoeRoomGeometry(state).legacy}));$('saved').textContent='Saved on this device ✓'}catch{$('saved').textContent='Not saved · download a copy';toast('Browser storage is unavailable. Download your decisions to keep them.')}}
function tab(id){document.querySelectorAll('.panel').forEach(x=>x.hidden=x.id!==id);document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===id);if(b.dataset.tab===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});history.replaceState(null,'','#'+id);if(id==='fit')drawPlan();if(id!=='room')$('walk').querySelector('iframe').src='about:blank';else if(view==='3d')picture();}
document.querySelectorAll('[data-tab],[data-go]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab||b.dataset.go)));
function picture(){document.querySelectorAll('[data-wall]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.wall===state.wall)));document.querySelectorAll('[data-metal]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.metal===state.metal)));$('floor').value=state.floor;$('mirror').value=state.mirror;$('pinned').textContent=state.pinned?'Kept: '+state.pinned:'Nothing is ordered when you make a choice.';if(view==='3d'){save();$('photoCaption').textContent='Illustrative 3D model. Drag to orbit. Floor and mirror choices appear here.';$('walk').querySelector('iframe').src='room3d.html';return}const tub=view==='tub';$('after').src=tub?'assets/after_tub.jpg':`assets/style_${state.wall}_${state.metal}.jpg`;$('before').src=tub?'assets/hall_tub.jpg':'assets/hall_vanity.jpg';$('after').alt=tub?'AI concept of Joe’s reglazed tub wall':`AI concept of Joe’s vanity wall in ${state.wall} with ${state.metal}`;$('photoCaption').textContent=tub?'Tub concept: white reglaze and retained sliders. Paint / metal controls preview the vanity wall.':'Real room photo + AI design concept. Finish preview, not a measured construction drawing.';floorPreview();}
document.querySelectorAll('[data-wall]').forEach(b=>b.onclick=()=>{state.wall=b.dataset.wall;save();picture();tick()});document.querySelectorAll('[data-metal]').forEach(b=>b.onclick=()=>{state.metal=b.dataset.metal;save();picture();tick()});['floor','mirror'].forEach(id=>$(id).onchange=()=>{state[id]=$(id).value;save();if(id==='floor'&&view==='tub')document.querySelector('[data-view="vanity"]').click();picture();budget();tick();if(id==='mirror'&&view!=='3d')toast('Mirror saved. Walk around to see its shape in 3D.')});
function floorPreview(){const svg=$('floorPreview');svg.hidden=state.floor==='keep'||view!=='vanity';if(svg.hidden)return;const oak=state.floor==='oak';svg.innerHTML=`<defs><clipPath id="floorClip"><polygon points="554,797 803,797 931,1045 406,1045"/></clipPath><pattern id="floorMaterial" width="${oak?100:220}" height="${oak?500:140}" patternUnits="userSpaceOnUse"><rect width="100%" height="100%" fill="${oak?'#bd9c70':'#b6b3a9'}"/>${oak?'<image href="assets/oak.jpg" width="100" height="500" preserveAspectRatio="xMidYMid slice"/>':'<path d="M0 0H220V140H0Z" fill="none" stroke="#dfdcd3" stroke-width="3"/><path d="M10 30Q100 10 180 65M40 110Q120 70 210 100" fill="none" stroke="#aaa89e" stroke-width="1"/>'}</pattern><linearGradient id="floorShadow" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#000" stop-opacity=".12"/><stop offset=".45" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity=".28"/></linearGradient></defs><g clip-path="url(#floorClip)"><rect x="400" y="790" width="540" height="260" fill="url(#floorMaterial)"/><rect x="400" y="790" width="540" height="260" fill="url(#floorShadow)"/></g>`;$('photoCaption').textContent='AI room concept + live floor-material overlay. Color and texture are illustrative; verify samples in your room.';}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('selected',x===b));$('picture').hidden=view==='3d';$('walk').hidden=view!=='3d';$('compareLabel').hidden=view==='3d';if(view!=='3d')$('walk').querySelector('iframe').src='about:blank';picture();});
$('compare').oninput=()=>{const v=+$('compare').value;$('beforeclip').style.clipPath=`inset(0 ${100-v}% 0 0)`;$('divider').style.left=v+'%';$('compareValue').textContent=v===0?'All possibility':v===100?'The original':`${v}% original`};
$('reveal').onclick=()=>{if(view==='3d')document.querySelector('[data-view="vanity"]').click();const on=$('picture').classList.toggle('evening');$('reveal').textContent=on?'Back to daylight ↗':'The evening reveal ↗';if(on){$('compare').value=0;$('compare').oninput();toast('The room you saw the possibility in. ♡');if(sound){const a=new Audio('assets/audio/warming_heart.mp3');a.play().catch(()=>tick())}}};
$('pin').onclick=()=>{state.pinned=`${{white:'Warm white',greige:'Soft greige',sage:'Quiet sage'}[state.wall]} + ${state.metal} · ${state.floor} floor · ${state.mirror} mirror`;save();picture();toast('Kept for you, Joe.');tick()};
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',sound);tick()};$('big').onclick=()=>{const on=document.body.classList.toggle('big');$('big').setAttribute('aria-pressed',on);try{localStorage.setItem('joe_bigtype',on?'1':'0')}catch{}};try{if(localStorage.getItem('joe_bigtype')==='1'){$('big').setAttribute('aria-pressed','true');document.body.classList.add('big')}}catch{}
function drawPlan(){const g=JoeRoomGeometry(state),w=g.width,l=g.length,t=g.tubDepth,tl=g.tubLength,scale=Math.min(480/w,390/l),ox=(700-w*scale)/2,oy=65;const X=v=>ox+v*scale,Y=v=>oy+v*scale;
$('gap').textContent=g.gap.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+'″';$('fitNote').textContent=(state.measured?'From your entered measurements. ':'Estimated until you measure. ')+(g.gap<0?'Fixture depths overlap. Recheck the dimensions.':`L-shaped floor: about ${g.area.toFixed(1)} sq ft, excluding the hall closet. This gap does not include drawer travel.`);
const outline=g.points.map(([x,y])=>X(x)+','+Y(y)).join(' '),vanY=Math.max(30,l-48.5-8);
$('plan').innerHTML=`<defs><pattern id="closethatch" width="9" height="9" patternUnits="userSpaceOnUse"><path d="M0 9L9 0" stroke="#bdc1b3" stroke-width="1"/></pattern></defs><rect x="${ox}" y="${Y(tl)}" width="${t*scale}" height="${(l-tl)*scale}" fill="url(#closethatch)"/><polygon points="${outline}" fill="#f9f8f1" stroke="#41594d" stroke-width="5"/><rect x="${ox}" y="${oy}" width="${t*scale}" height="${tl*scale}" fill="#e0e8e4" stroke="#7d9587" stroke-width="2"/><rect x="${X(3)}" y="${Y(5)}" width="${(t-6)*scale}" height="${(tl-10)*scale}" rx="22" fill="#fff"/><line x1="${X(t)}" y1="${oy}" x2="${X(t)}" y2="${Y(tl)}" stroke="#8aa4a1" stroke-width="3"/><text x="${X(t/2)}" y="${Y(tl/2)}" text-anchor="middle" fill="#253b34" font-size="17" transform="rotate(-90 ${X(t/2)} ${Y(tl/2)})">Tub · flush in corner</text><text x="${X(t/2)}" y="${Y(tl+(l-tl)/2)-7}" text-anchor="middle" font-size="16" fill="#59604f">HALL</text><text x="${X(t/2)}" y="${Y(tl+(l-tl)/2)+14}" text-anchor="middle" font-size="16" fill="#59604f">CLOSET</text><rect x="${X(w-18.75)}" y="${Y(vanY)}" width="${18.75*scale}" height="${48.5*scale}" fill="#cfbfa5" stroke="#65725e"/><text x="${X(w-9)}" y="${Y(vanY+24.25)}" text-anchor="middle" font-size="15" fill="#253b34" transform="rotate(-90 ${X(w-9)} ${Y(vanY+24.25)})">48½″ vanity · bought</text><rect x="${X(w-10)}" y="${Y(4)}" width="${9*scale}" height="${20*scale}" rx="4" fill="#fff" stroke="#99a596"/><ellipse cx="${X(w-18)}" cy="${Y(14)}" rx="${12*scale}" ry="${9*scale}" fill="#fff" stroke="#99a596"/><text x="${X(w-17)}" y="${Y(32)}" text-anchor="middle" font-size="15" fill="#253b34">Toilet corner</text><path d="M${X(t)} ${Y(tl-8)}H${X(w-18.75)}" stroke="#a77243" stroke-dasharray="4 3" stroke-width="2"/><text x="${X(t+(w-18.75-t)/2)}" y="${Y(tl-8)-9}" text-anchor="middle" font-size="16" fill="#80542c">${g.gap.toFixed(1)}″</text><path d="M${X(t+2)} ${Y(l)}H${X(Math.min(w-2,t+30))}" stroke="#f9f8f1" stroke-width="7"/><text x="${X(t+(w-t)/2)}" y="${Y(l)+30}" text-anchor="middle" font-size="16" fill="#253b34">EXISTING DOOR · stays here</text><text x="350" y="30" text-anchor="middle" font-size="18" fill="#253b34">BACK / WINDOW · ${w}″ estimated width</text><text x="${X(w)+20}" y="${Y(l/2)}" font-size="17" fill="#253b34" transform="rotate(90 ${X(w)+20} ${Y(l/2)})">${l}″ outer length</text>`;
}
['width','length','tubLength','tubDepth','ceiling','reserve'].forEach(id=>{$(id).value=state[id];$(id).onchange=()=>{const v=+$(id).value,min=+$(id).min,max=$(id).max?+$(id).max:1000000;if(!Number.isFinite(v)||v<min||v>max){$(id).value=state[id];toast('Please enter a number within the stated range.');return}if((id==='length'&&v<=state.tubLength)||(id==='tubLength'&&v>=state.length)||(id==='width'&&v<=state.tubDepth)||(id==='tubDepth'&&v>=state.width)){$(id).value=state[id];toast('The outer room must extend beyond the tub alcove.');return}state[id]=v;save();drawPlan();budget()}});$('measured').checked=state.measured;$('measured').onchange=()=>{state.measured=$('measured').checked;save();drawPlan()};
function budget(){let all=0,unpaid=0;for(const [id]of costs){const c=state.costs[id];all+=c.amount;if(c.status!=='paid')unpaid+=c.amount}const contingency=unpaid*state.reserve/100,total=all+contingency,left=state.ceiling-total;$('total').textContent=money(total);$('remaining').textContent=money(unpaid+contingency);$('headroom').textContent=money(Math.abs(left));$('headroomLabel').textContent=left<0?'OVER CEILING':'ROOM LEFT';$('headroom').style.color=left<0?'#9e3b2a':'';$('budgetFill').style.width=Math.min(100,state.ceiling?total/state.ceiling*100:100)+'%';$('budgetFill').style.background=left<0?'#9e3b2a':'#71846b';$('budgetNote').textContent=`${money(contingency)} reserve on unpaid work. ${state.costs.vanity.amount===0?'Vanity is already bought; its receipt amount is not entered, so the full project total is incomplete.':'Vanity purchase is included in the project total and excluded from still-to-pay.'}${state.floor!=='keep'&&state.costs.flooring.amount===0?' New floor selected: replacement cost is not entered yet. Add a quote before relying on the total.':''}`;}
for(const[id,title,desc]of costs){const row=document.createElement('div');row.className='costrow';const d=document.createElement('div');const strong=document.createElement('strong');strong.textContent=title;const p=document.createElement('p');p.textContent=desc;d.append(strong,p);const l=document.createElement('label');l.textContent='Amount ($)';const input=document.createElement('input');input.type='number';input.min='0';input.step='1';input.value=state.costs[id].amount;input.setAttribute('aria-label',title+' amount');input.onchange=()=>{if(!Number.isFinite(+input.value)||+input.value<0){input.value=state.costs[id].amount;return}state.costs[id].amount=+input.value;save();budget()};l.append(input);const sl=document.createElement('label');sl.textContent='Status';const s=document.createElement('select');for(const v of ['allowance','quoted','paid']){const o=document.createElement('option');o.value=v;o.textContent={allowance:'Estimate',quoted:'Written quote',paid:'Paid / owned'}[v];s.append(o)}s.value=state.costs[id].status;s.disabled=id==='vanity';s.onchange=()=>{state.costs[id].status=s.value;save();budget()};sl.append(s);row.append(d,l,sl);$('costs').append(row)}
const steps=[['Measure the real room','JOE','Tape the walls and clearances. Photograph the vanity label in the garage.'],['Check the mounting and plumbing','JOE + INSTALLER','Confirm blocking, drain alignment, faucet fit and the included parts. Keep the existing door in place.'],['Choose the written scope','JOE','Compare reglaze quotes. Record coating, preparation, ventilation, warranty and cure time.'],['Prepare in the agreed order','TOGETHER + PRO','Agree paint, repairs, installation and refinishing sequence with the trades. Protect what stays.'],['Let the finish cure','FOLLOW THE COATING INSTRUCTIONS','Use the contractor’s written times for re-entry and use. Do not guess from a generic countdown.'],['Finish, check, enjoy','JOE + GORDON','Check leaks and fixings, fit the finishing touches, keep the aftercare sheet.']];
function renderSteps(){$('steps').replaceChildren();let done=0;steps.forEach(([title,who,desc],i)=>{const row=document.createElement('label');row.className='step';const c=document.createElement('input');c.type='checkbox';c.checked=!!state.steps[i];if(c.checked)done++;c.onchange=()=>{state.steps[i]=c.checked;save();renderSteps();tick()};const n=document.createElement('span');n.className='num';n.textContent=String(i+1).padStart(2,'0');const d=document.createElement('div');const h=document.createElement('strong');h.textContent=title;const p=document.createElement('p');p.textContent=who+' · '+desc;d.append(h,p);row.append(c,n,d);$('steps').append(row)});$('doneCount').textContent=done+' / 6';const next=steps.findIndex((_,i)=>!state.steps[i]);$('nextAction').textContent=next<0?'All six checked. Enjoy what you made, Joe.':'Next up: '+steps[next][0]+'.';}
for(const id of ['likes','changes','questions']){$(id).value=state.notes[id];$(id).oninput=()=>{state.notes[id]=$(id).value;save()}}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'joes-room-v2',savedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='Joes-room-decisions.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Your decisions are ready to keep.')};
$('import').onchange=async()=>{try{const f=$('import').files[0];if(!f)return;if(f.size>100000)throw Error();const d=JSON.parse(await f.text());if(d.format!=='joes-room-v2'||!d.state)throw Error();const s=d.state;for(const[k,min,max]of [['width',40,180],['length',60,240],['tubDepth',20,48],['tubLength',40,100],['ceiling',0,1000000],['reserve',0,50]])if(typeof s[k]!=='number'||s[k]<min||s[k]>max)throw Error();for(const[k,v]of Object.entries({wall:['white','greige','sage'],metal:['chrome','brass'],floor:['keep','stone','oak'],mirror:['framed','lit','cabinet']}))if(!v.includes(s[k]))throw Error();for(const[k]of costs)if(!s.costs?.[k]||typeof s.costs[k].amount!=='number'||s.costs[k].amount<0||!['allowance','quoted','paid'].includes(s.costs[k].status))throw Error();if(!s.notes||!['likes','changes','questions'].every(k=>typeof s.notes[k]==='string')||!Array.isArray(s.steps)||typeof s.pinned!=='string')throw Error();state=s;state.costs.vanity.status='paid';save();location.reload()}catch{$('importStatus').textContent='That file could not be restored. Your current choices are safe.'}};
$('print').onclick=$('printBudget').onclick=()=>window.print();window.addEventListener('storage',e=>{if(e.key===LEGACY)toast('The original planner changed. Reload to review your saved room dimensions.')} );
save();picture();drawPlan();budget();renderSteps();tab(['room','fit','money','build','notes'].includes(location.hash.slice(1))?location.hash.slice(1):'room');
